- name: Instalacja ADDS w nowym lesie
  hosts: windows
  gather_facts: false

  vars_files:
    - secrets.yml  

  vars:
    domain_name: "adds.IaC.pl"          
    safe_mode_password: "{{ dsrm_password }}"  

  tasks:
  
    - name: Instaluj ADDS oraz DNS
      ansible.windows.win_feature:
        name:
          - AD-Domain-Services
          - DNS
        state: present
        include_management_tools: true

    - name: Stworz nowy LAS
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        reboot: true
        reboot_timeout: 1800
      
    - name: Dodanie rekordu dns
      ansible.windows.win_dns_record:
        zone: "{{ domain_name }}"
        name: "linux"
        type: "A"
        value: "172.22.1.11"
        state: present

    - name: Dodanie rekordu dns
      ansible.windows.win_dns_record:
        zone: "{{ domain_name }}"
        name: "sklep.local"
        type: "A"
        value: "172.22.1.10"
        state: present